### ISSUE TITLE
Fail to install qwen-chat-14B

### ISSUE THREAD

**Issue by netty1916** [xorbitsai/inference#1003]
### To Reproduce

1. Python version: 3.10
2. The version of xinference : 0.8.5
3. Versions of crucial packages.
>>> print(torch.__version__)：2.2.0
>>> print(torch.version.cuda)：12.1
>>> print(torch.backends.cudnn.version()) ：8902
>>> torch.cuda.get_arch_list()：['sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'sm_90']

4. Full stack of the error.
2024-02-12 15:40:02,255 xinference.model.llm.core 61 DEBUG    Launching qwen-chat-1-0 with VLLMChatModel
2024-02-12 15:40:02,278 xinference.model.llm.vllm.core 435 INFO     Loading qwen-chat with following model config: {'tokenizer_mode': 'auto', 'trust_remote_code': True, 'tensor_parallel_size': 1, 'block_size': 16, 'swap_space': 4, 'gpu_memory_utilization': 0.9, 'max_num_seqs': 256, 'quantization': None, 'max_model_len': 4096}
2024-02-12 15:40:02,299 xinference.core.worker 61 ERROR    Failed to load model qwen-chat-1-0

  File "/opt/conda/lib/python3.10/site-packages/xinference/model/llm/vllm/core.py", line 139, in load
    self._engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/opt/conda/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 617, in from_engine_args
    engine_configs = engine_args.create_engine_configs()
  File "/opt/conda/lib/python3.10/site-packages/vllm/engine/arg_utils.py", line 272, in create_engine_configs
    model_config = ModelConfig(self.model, self.tokenizer,
  File "/opt/conda/lib/python3.10/site-packages/vllm/config.py", line 105, in __init__
    self.max_model_len = _get_and_verify_max_len(self.hf_config,
  File "/opt/conda/lib/python3.10/site-packages/vllm/config.py", line 603, in _get_and_verify_max_len
    raise ValueError(
ValueError: [address=0.0.0.0:40940, pid=435] User-specified max_model_len (4096) is greater than the derived max_model_len (None=2048 in model's config.json). This may lead to incorrect model outputs or CUDA errors. Make sure the value is correct and within the model context size.

### Expected behavior

Please help with the successful deployment of the model.

### Additional context
1）、GPU: NVIDIA RTX A6000 
2)、Launching the Qwen model directly with the Python command in the same environment is successful.

**Comment by aresnow1** [comment]
How did you launch model?

**Comment by netty1916** [comment]
launching with ui.
The issue has been resolved after modifying max_model_len to 2048, as referenced in 
inference-0.8.5/xinference/model/llm/vllm/core.py.
Thanks!

**Comment by qinxuye** [comment]
Now you can pass extra params to vllm, close first.
