### ISSUE TITLE
Docker部署Xinference时显示无GPU（实际有）

### ISSUE THREAD

**Issue by Kyrie-LiuX** [xorbitsai/inference#1778]
Note that the issue tracker is NOT the place for general support.
我输入nvidia-smi可以看到我的显卡信息，但是：
(base) dell@dell:sudo docker run -e HF_ENDPOINT=https://hf-mirror.com/ -e XINFERENCE_MODEL_SRC=modelscope -p 9998:9997 --gpus all xprobe/xinference
xinference-local -H 0.0.0.0 --log-level debug
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
ERRO[0000] error waiting for container:
(base) dell@dell:sudo apt-get install -y nvidia-container-toolkit
正在读取软件包列表... 完成
正在分析软件包的依赖关系树
正在读取状态信息... 完成
E: 无法定位软件包 nvidia-container-toolkit

我不知道如何解决这个问题，还请您指教，谢谢！

**Comment by Valdanitooooo** [comment]
有重启 docker 服务吗

**Comment by ChengjieLi28** [comment]
@Kyrie-LiuX 
```
(base) dell@dell:sudo apt-get install -y nvidia-container-toolkit
正在读取软件包列表... 完成
正在分析软件包的依赖关系树
正在读取状态信息... 完成
E: 无法定位软件包 nvidia-container-toolkit
```
先把安装这个的问题解决，再启动docker就行了。你可能要先执行
```
sudo apt-get update
```

**Comment by navi-avatar** [comment]
我也遇到了，通过这个网址，安装container-toolkit 就可以了
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/1.15.0/install-guide.html
