### ISSUE TITLE
偶发性报错 xinference.api.restful_api 164241 ERROR    Remote server 0.0.0.0:44339 closed

### ISSUE THREAD

**Issue by JinCheng666** [xorbitsai/inference#1896]
### System Info / 系統信息

cuda12.1
torch                             2.3.0
transformers                      4.42.4
vllm                              0.5.1
xinference                        0.13.1
xoscar                            0.3.2
python        3.10
Ubuntu       20.04
GPU配置为：2*A6000，没有nvlink
电脑cpu和内存是虚拟化出来，GPU是直通的

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] pip install / 通过 pip install 安装

### Version info / 版本信息

0.13.1

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 9997 --log-level DEBUG

模型启动
![image](https://github.com/user-attachments/assets/43fc6949-0b66-4715-b828-417a48bef6a2)

### Reproduction / 复现过程

暂无明确的复现步骤，推测是高并发时，偶发性会出现72b无法回复的问题，后台报错如下：
2024-07-19 09:08:50,484 xinference.api.restful_api 164241 ERROR    Remote server 0.0.0.0:44339 closed
Traceback (most recent call last):
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1613, in create_chat_completion
    data = await model.chat(
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 230, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 0.0.0.0:44339 closed
2024-07-19 09:08:50,485 xinference.api.restful_api 164241 ERROR    Remote server 0.0.0.0:44339 closed

### 详细报错
```bash
2024-07-19 09:08:29,338 uvicorn.access 164241 INFO     127.0.0.1:46334 - "GET /v1/cluster/auth HTTP/1.1" 200
2024-07-19 09:08:29,340 xinference.core.supervisor 164311 DEBUG    Enter describe_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fa6360afa10>, 'qwen2:7b'), kwargs: {}
2024-07-19 09:08:29,341 xinference.core.worker 164311 DEBUG    Enter describe_model, args: (<xinference.core.worker.WorkerActor object at 0x7fa56b519490>,), kwargs: {'model_uid': 'qwen2:7b-1-0'}
2024-07-19 09:08:29,341 xinference.core.worker 164311 DEBUG    Leave describe_model, elapsed time: 0 s
2024-07-19 09:08:29,341 xinference.core.supervisor 164311 DEBUG    Leave describe_model, elapsed time: 0 s
2024-07-19 09:08:29,342 uvicorn.access 164241 INFO     127.0.0.1:46336 - "GET /v1/models/qwen2%3A7b HTTP/1.1" 200
2024-07-19 09:08:29,344 xinference.core.supervisor 164311 DEBUG    Enter get_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fa6360afa10>, 'qwen2:7b'), kwargs: {}
2024-07-19 09:08:29,344 xinference.core.worker 164311 DEBUG    Enter get_model, args: (<xinference.core.worker.WorkerActor object at 0x7fa56b519490>,), kwargs: {'model_uid': 'qwen2:7b-1-0'}
2024-07-19 09:08:29,344 xinference.core.worker 164311 DEBUG    Leave get_model, elapsed time: 0 s
2024-07-19 09:08:29,344 xinference.core.supervisor 164311 DEBUG    Leave get_model, elapsed time: 0 s
2024-07-19 09:08:29,345 xinference.core.supervisor 164311 DEBUG    Enter describe_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fa6360afa10>, 'qwen2:7b'), kwargs: {}
2024-07-19 09:08:29,345 xinference.core.worker 164311 DEBUG    Enter describe_model, args: (<xinference.core.worker.WorkerActor object at 0x7fa56b519490>,), kwargs: {'model_uid': 'qwen2:7b-1-0'}
2024-07-19 09:08:29,345 xinference.core.worker 164311 DEBUG    Leave describe_model, elapsed time: 0 s
2024-07-19 09:08:29,345 xinference.core.supervisor 164311 DEBUG    Leave describe_model, elapsed time: 0 s
2024-07-19 09:08:29,346 uvicorn.access 164241 INFO     127.0.0.1:46338 - "POST /v1/chat/completions HTTP/1.1" 200
2024-07-19 09:08:29,346 xinference.core.model 164770 DEBUG    Enter wrapped_func, args: (<xinference.core.model.ModelActor object at 0x7f0024eb8860>, '你是谁', '', [], {'max_tokens': 512, 'temperature': 1.0, 'stream': True, 'lora_name': ''}), kwargs: {'raw_params': {'max_tokens': 512, 'temperature': 1, 'stream': True, 'lora_name': ''}}
2024-07-19 09:08:29,347 xinference.core.model 164770 DEBUG    Request chat, current serve request count: 0, request limit: None for the model qwen2:7b
2024-07-19 09:08:29,347 xinference.model.llm.vllm.core 164770 DEBUG    Enter generate, prompt: <|im_start|>system
You are a helpful assistant.<|im_end|>
<|im_start|>user
你是谁<|im_end|>
<|im_start|>assistant
, generate config: {'max_tokens': 512, 'temperature': 1.0, 'stream': True, 'lora_name': '', 'stop': ['<|endoftext|>', '<|im_start|>', '<|im_end|>'], 'stop_token_ids': [151643, 151644, 151645]}
2024-07-19 09:08:29,347 xinference.core.model 164770 DEBUG    After request chat, current serve request count: 0 for the model qwen2:7b
2024-07-19 09:08:29,347 xinference.core.model 164770 DEBUG    Leave wrapped_func, elapsed time: 0 s
2024-07-19 09:08:29,348 vllm.engine.async_llm_engine 164770 INFO     Received request 68c72856-456b-11ef-9af1-0cda411d272a: prompt: '<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n<|im_start|>user\n你是谁<|im_end|>\n<|im_start|>assistant\n', params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=1.0, top_p=1.0, top_k=-1, min_p=0.0, seed=None, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=['<|endoftext|>', '<|im_start|>', '<|im_end|>'], stop_token_ids=[151643, 151644, 151645], include_stop_str_in_output=False, ignore_eos=False, max_tokens=512, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True, truncate_prompt_tokens=None), prompt_token_ids: None, lora_request: None.
2024-07-19 09:08:29,349 vllm.engine.async_llm_engine 164770 DEBUG    Got new requests!
2024-07-19 09:08:29,380 vllm.engine.metrics 164770 INFO     Avg prompt throughput: 0.2 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%.
2024-07-19 09:08:29,938 vllm.engine.async_llm_engine 164770 INFO     Finished request 68c72856-456b-11ef-9af1-0cda411d272a.
2024-07-19 09:08:29,939 vllm.engine.async_llm_engine 164770 DEBUG    Waiting for new requests...
2024-07-19 09:08:30,004 uvicorn.access 164241 INFO     10.4.134.25:12101 - "POST /qwen2%3A7b/run/predict HTTP/1.1" 200
2024-07-19 09:08:31,311 vllm.engine.metrics 164485 INFO     Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 29.9 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 14 reqs, GPU KV cache usage: 94.0%, CPU KV cache usage: 0.0%.
2024-07-19 09:08:35,105 vllm.engine.async_llm_engine 164485 INFO     Finished request 6f65918a-456a-11ef-a8df-0cda411d272a.
2024-07-19 09:08:35,109 xinference.core.model 164485 DEBUG    After request chat, current serve request count: 0 for the model qwen:72b
2024-07-19 09:08:35,109 xinference.core.model 164485 DEBUG    Leave wrapped_func, elapsed time: 424 s
2024-07-19 09:08:39,050 vllm.engine.metrics 164485 INFO     Avg prompt throughput: 321.4 tokens/s, Avg generation throughput: 14.9 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 13 reqs, GPU KV cache usage: 86.0%, CPU KV cache usage: 0.0%.
2024-07-19 09:08:44,109 vllm.engine.metrics 164485 INFO     Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 30.0 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 13 reqs, GPU KV cache usage: 88.1%, CPU KV cache usage: 0.0%.
2024-07-19 09:08:49,114 vllm.engine.metrics 164485 INFO     Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 30.0 tokens/s, Running: 2 reqs, Swapped: 0 reqs, Pending: 13 reqs, GPU KV cache usage: 90.2%, CPU KV cache usage: 0.0%.
2024-07-19 09:08:50,471 xinference.core.supervisor 164311 DEBUG    Enter terminate_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fa6360afa10>, 'qwen:72b'), kwargs: {}
2024-07-19 09:08:50,472 xinference.core.worker 164311 DEBUG    Enter terminate_model, args: (<xinference.core.worker.WorkerActor object at 0x7fa56b519490>,), kwargs: {'model_uid': 'qwen:72b-1-0'}
2024-07-19 09:08:50,484 xinference.api.restful_api 164241 ERROR    Remote server 0.0.0.0:44339 closed
Traceback (most recent call last):
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1613, in create_chat_completion
    data = await model.chat(
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 230, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 0.0.0.0:44339 closed
2024-07-19 09:08:50,485 xinference.api.restful_api 164241 ERROR    Remote server 0.0.0.0:44339 closed
Traceback (most recent call last):
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1613, in create_chat_completion
    data = await model.chat(
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 230, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 0.0.0.0:44339 closed
2024-07-19 09:08:50,486 xinference.api.restful_api 164241 ERROR    Remote server 0.0.0.0:44339 closed
Traceback (most recent call last):
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1613, in create_chat_completion
    data = await model.chat(
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 230, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 0.0.0.0:44339 closed
2024-07-19 09:08:50,486 xinference.api.restful_api 164241 ERROR    Remote server 0.0.0.0:44339 closed
Traceback (most recent call last):
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1613, in create_chat_completion
    data = await model.chat(
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 230, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 0.0.0.0:44339 closed
2024-07-19 09:08:50,486 xinference.api.restful_api 164241 ERROR    Remote server 0.0.0.0:44339 closed
Traceback (most recent call last):
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1613, in create_chat_completion
    data = await model.chat(
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 230, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 0.0.0.0:44339 closed
2024-07-19 09:08:50,487 xinference.api.restful_api 164241 ERROR    Remote server 0.0.0.0:44339 closed
Traceback (most recent call last):
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1613, in create_chat_completion
    data = await model.chat(
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 230, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 0.0.0.0:44339 closed
2024-07-19 09:08:50,487 xinference.api.restful_api 164241 ERROR    Remote server 0.0.0.0:44339 closed
Traceback (most recent call last):
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1613, in create_chat_completion
    data = await model.chat(
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 230, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 0.0.0.0:44339 closed
2024-07-19 09:08:50,487 xinference.api.restful_api 164241 ERROR    Remote server 0.0.0.0:44339 closed
Traceback (most recent call last):
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1613, in create_chat_completion
    data = await model.chat(
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 230, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 0.0.0.0:44339 closed
2024-07-19 09:08:50,488 xinference.api.restful_api 164241 ERROR    Remote server 0.0.0.0:44339 closed
Traceback (most recent call last):
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1613, in create_chat_completion
    data = await model.chat(
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 230, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 0.0.0.0:44339 closed
2024-07-19 09:08:50,488 xinference.api.restful_api 164241 ERROR    Remote server 0.0.0.0:44339 closed
Traceback (most recent call last):
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1613, in create_chat_completion
    data = await model.chat(
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 230, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 0.0.0.0:44339 closed
2024-07-19 09:08:50,488 xinference.api.restful_api 164241 ERROR    Remote server 0.0.0.0:44339 closed
Traceback (most recent call last):
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1613, in create_chat_completion
    data = await model.chat(
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 230, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 0.0.0.0:44339 closed
2024-07-19 09:08:50,488 xinference.api.restful_api 164241 ERROR    Remote server 0.0.0.0:44339 closed
Traceback (most recent call last):
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1613, in create_chat_completion
    data = await model.chat(
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 230, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 0.0.0.0:44339 closed
2024-07-19 09:08:50,489 xinference.api.restful_api 164241 ERROR    Remote server 0.0.0.0:44339 closed
Traceback (most recent call last):
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1613, in create_chat_completion
    data = await model.chat(
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 230, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 0.0.0.0:44339 closed
2024-07-19 09:08:50,489 xinference.api.restful_api 164241 ERROR    Remote server 0.0.0.0:44339 closed
Traceback (most recent call last):
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1613, in create_chat_completion
    data = await model.chat(
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 230, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 0.0.0.0:44339 closed
2024-07-19 09:08:50,489 xinference.api.restful_api 164241 ERROR    Chat completion stream got an error: Remote server 0.0.0.0:44339 closed
Traceback (most recent call last):
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1584, in stream_results
    async for item in iterator:
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/api.py", line 340, in __anext__
    return await self._actor_ref.__xoscar_next__(self._uid)
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 230, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 0.0.0.0:44339 closed
2024-07-19 09:08:51,308 xinference.core.worker 164311 DEBUG    Leave terminate_model, elapsed time: 0 s
2024-07-19 09:08:51,308 xinference.core.supervisor 164311 DEBUG    Leave terminate_model, elapsed time: 0 s
2024-07-19 09:08:51,309 uvicorn.access 164241 INFO     10.4.134.25:12111 - "DELETE /v1/models/qwen%3A72b HTTP/1.1" 200
2024-07-19 09:08:51,325 xinference.core.supervisor 164311 DEBUG    Enter list_models, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fa6360afa10>,), kwargs: {}
2024-07-19 09:08:51,325 xinference.core.worker 164311 DEBUG    Enter list_models, args: (<xinference.core.worker.WorkerActor object at 0x7fa56b519490>,), kwargs: {}
2024-07-19 09:08:51,325 xinference.core.worker 164311 DEBUG    Leave list_models, elapsed time: 0 s
2024-07-19 09:08:51,325 xinference.core.supervisor 164311 DEBUG    Leave list_models, elapsed time: 0 s
2024-07-19 09:08:51,326 uvicorn.access 164241 INFO     10.4.134.25:12111 - "GET /v1/models HTTP/1.1" 200
2024-07-19 09:09:08,669 xinference.core.supervisor 164311 DEBUG    Enter list_model_registrations, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fa6360afa10>, 'LLM'), kwargs: {'detailed': True}
2024-07-19 09:09:08,670 uvicorn.access 164241 INFO     10.4.134.25:12121 - "GET /v1/cluster/devices HTTP/1.1" 200
2024-07-19 09:09:08,778 xinference.core.supervisor 164311 DEBUG    Leave list_model_registrations, elapsed time: 0 s
2024-07-19 09:09:08,788 uvicorn.access 164241 INFO     10.4.134.25:12120 - "GET /v1/model_registrations/LLM?detailed=true HTTP/1.1" 200
2024-07-19 09:09:23,805 xinference.core.supervisor 164311 DEBUG    Enter list_model_registrations, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fa6360afa10>, 'LLM'), kwargs: {'detailed': False}
2024-07-19 09:09:23,806 xinference.core.supervisor 164311 DEBUG    Leave list_model_registrations, elapsed time: 0 s
2024-07-19 09:09:23,807 uvicorn.access 164241 INFO     10.4.134.25:12122 - "GET /v1/model_registrations/LLM HTTP/1.1" 200
2024-07-19 09:09:23,815 xinference.core.supervisor 164311 DEBUG    Enter get_model_registration, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fa6360afa10>, 'LLM', 'glm-4-9b'), kwargs: {}
2024-07-19 09:09:23,815 xinference.core.supervisor 164311 DEBUG    Leave get_model_registration, elapsed time: 0 s
2024-07-19 09:09:23,816 uvicorn.access 164241 INFO     10.4.134.25:12122 - "GET /v1/model_registrations/LLM/glm-4-9b HTTP/1.1" 200
2024-07-19 09:09:23,817 xinference.core.supervisor 164311 DEBUG    Enter get_model_registration, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fa6360afa10>, 'LLM', 'glm-4v-9b'), kwargs: {}
2024-07-19 09:09:23,817 xinference.core.supervisor 164311 DEBUG    Leave get_model_registration, elapsed time: 0 s
2024-07-19 09:09:23,818 xinference.core.supervisor 164311 DEBUG    Enter get_model_registration, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fa6360afa10>, 'LLM', 'llama3:70b'), kwargs: {}
2024-07-19 09:09:23,818 xinference.core.supervisor 164311 DEBUG    Leave get_model_registration, elapsed time: 0 s
2024-07-19 09:09:23,818 xinference.core.supervisor 164311 DEBUG    Enter get_model_registration, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fa6360afa10>, 'LLM', 'qwen2:7b'), kwargs: {}
2024-07-19 09:09:23,819 xinference.core.supervisor 164311 DEBUG    Leave get_model_registration, elapsed time: 0 s
2024-07-19 09:09:23,819 xinference.core.supervisor 164311 DEBUG    Enter get_model_registration, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fa6360afa10>, 'LLM', 'qwen1.5:14b'), kwargs: {}
2024-07-19 09:09:23,819 xinference.core.supervisor 164311 DEBUG    Leave get_model_registration, elapsed time: 0 s
2024-07-19 09:09:23,819 uvicorn.access 164241 INFO     10.4.134.25:12123 - "GET /v1/model_registrations/LLM/glm-4v-9b HTTP/1.1" 200
2024-07-19 09:09:23,819 xinference.core.supervisor 164311 DEBUG    Enter get_model_registration, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fa6360afa10>, 'LLM', 'qwen1.5:72b'), kwargs: {}
2024-07-19 09:09:23,820 xinference.core.supervisor 164311 DEBUG    Leave get_model_registration, elapsed time: 0 s
2024-07-19 09:09:23,820 uvicorn.access 164241 INFO     10.4.134.25:12124 - "GET /v1/model_registrations/LLM/llama3%3A70b HTTP/1.1" 200
2024-07-19 09:09:23,820 uvicorn.access 164241 INFO     10.4.134.25:12122 - "GET /v1/model_registrations/LLM/qwen2%3A7b HTTP/1.1" 200
2024-07-19 09:09:23,820 uvicorn.access 164241 INFO     10.4.134.25:12125 - "GET /v1/model_registrations/LLM/qwen1.5%3A14b HTTP/1.1" 200
2024-07-19 09:09:23,821 uvicorn.access 164241 INFO     10.4.134.25:12126 - "GET /v1/model_registrations/LLM/qwen1.5%3A72b HTTP/1.1" 200
2024-07-19 09:09:23,822 xinference.core.supervisor 164311 DEBUG    Enter get_model_registration, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fa6360afa10>, 'LLM', 'qwen:110b'), kwargs: {}
2024-07-19 09:09:23,822 xinference.core.supervisor 164311 DEBUG    Leave get_model_registration, elapsed time: 0 s
2024-07-19 09:09:23,823 uvicorn.access 164241 INFO     10.4.134.25:12123 - "GET /v1/model_registrations/LLM/qwen%3A110b HTTP/1.1" 200
2024-07-19 09:09:23,823 xinference.core.supervisor 164311 DEBUG    Enter get_model_registration, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fa6360afa10>, 'LLM', 'qwen:72b'), kwargs: {}
2024-07-19 09:09:23,823 xinference.core.supervisor 164311 DEBUG    Leave get_model_registration, elapsed time: 0 s
2024-07-19 09:09:23,823 uvicorn.access 164241 INFO     10.4.134.25:12124 - "GET /v1/model_registrations/LLM/qwen%3A72b HTTP/1.1" 200
2024-07-19 09:09:27,990 xinference.core.supervisor 164311 DEBUG    Enter query_engines_by_model_name, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fa6360afa10>, 'qwen:72b'), kwargs: {}
2024-07-19 09:09:27,991 xinference.core.worker 164311 DEBUG    Enter query_engines_by_model_name, args: (<xinference.core.worker.WorkerActor object at 0x7fa56b519490>, 'qwen:72b'), kwargs: {}
2024-07-19 09:09:27,991 xinference.core.worker 164311 DEBUG    Leave query_engines_by_model_name, elapsed time: 0 s
2024-07-19 09:09:27,991 xinference.core.supervisor 164311 DEBUG    Leave query_engines_by_model_name, elapsed time: 0 s
2024-07-19 09:09:27,992 uvicorn.access 164241 INFO     10.4.134.25:12124 - "GET /v1/engines/qwen%3A72b HTTP/1.1" 200
2024-07-19 09:09:30,313 xinference.core.supervisor 164311 DEBUG    Enter launch_builtin_model, model_uid: qwen:72b, model_name: qwen:72b, model_size: 72, model_format: gptq, quantization: Int4, replica: 1, kwargs: {}
2024-07-19 09:09:30,314 xinference.core.worker 164311 DEBUG    Enter get_model_count, args: (<xinference.core.worker.WorkerActor object at 0x7fa56b519490>,), kwargs: {}
2024-07-19 09:09:30,314 xinference.core.worker 164311 DEBUG    Leave get_model_count, elapsed time: 0 s
2024-07-19 09:09:30,314 xinference.core.worker 164311 DEBUG    Enter launch_builtin_model, args: (<xinference.core.worker.WorkerActor object at 0x7fa56b519490>,), kwargs: {'model_uid': 'qwen:72b-1-0', 'model_name': 'qwen:72b', 'model_size_in_billions': 72, 'model_format': 'gptq', 'quantization': 'Int4', 'model_engine': 'vLLM', 'model_type': 'LLM', 'n_gpu': 'auto', 'request_limits': None, 'peft_model_config': None, 'gpu_idx': None, 'download_hub': None}
2024-07-19 09:09:30,314 xinference.core.worker 164311 DEBUG    GPU selected: [0] for model qwen:72b-1-0
2024-07-19 09:09:33,787 xinference.model.llm.core 164311 DEBUG    Launching qwen:72b-1-0 with VLLMChatModel
2024-07-19 09:09:33,787 xinference.model.llm.llm_family 164311 INFO     Caching from URI: /home/gx01/models/Qwen2-72B-Instruct-GPTQ-Int4
2024-07-19 09:09:33,788 xinference.model.llm.llm_family 164311 INFO     Cache /home/gx01/models/Qwen2-72B-Instruct-GPTQ-Int4 exists
2024-07-19 09:09:33,805 xinference.model.llm.vllm.core 968639 INFO     Loading qwen:72b with following model config: {'tokenizer_mode': 'auto', 'trust_remote_code': True, 'tensor_parallel_size': 1, 'block_size': 16, 'swap_space': 4, 'gpu_memory_utilization': 0.9, 'max_num_seqs': 256, 'quantization': None, 'max_model_len': 4096}Enable lora: False. Lora count: 0.
2024-07-19 09:09:33,807 transformers.configuration_utils 968639 INFO     loading configuration file /home/gx01/models/Qwen2-72B-Instruct-GPTQ-Int4/config.json
2024-07-19 09:09:33,809 transformers.configuration_utils 968639 INFO     Model config Qwen2Config {
  "_name_or_path": "/home/gx01/models/Qwen2-72B-Instruct-GPTQ-Int4",
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 8192,
  "initializer_range": 0.02,
  "intermediate_size": 29696,
  "max_position_embeddings": 32768,
  "max_window_layers": 70,
  "model_type": "qwen2",
  "num_attention_heads": 64,
  "num_hidden_layers": 80,
  "num_key_value_heads": 8,
  "quantization_config": {
    "batch_size": 1,
    "bits": 4,
    "block_name_to_quantize": null,
    "cache_block_outputs": true,
    "damp_percent": 0.01,
    "dataset": null,
    "desc_act": false,
    "exllama_config": {
      "version": 1
    },
    "group_size": 128,
    "max_input_length": null,
    "model_seqlen": null,
    "module_name_preceding_first_block": null,
    "modules_in_block_to_quantize": null,
    "pad_token_id": null,
    "quant_method": "gptq",
    "sym": true,
    "tokenizer": null,
    "true_sequential": true,
    "use_cuda_fp16": false,
    "use_exllama": true
  },
  "rms_norm_eps": 1e-06,
  "rope_theta": 1000000.0,
  "sliding_window": 131072,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.42.4",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 152064
}

2024-07-19 09:09:33,817 vllm.model_executor.layers.quantization.gptq_marlin 968639 INFO     The model is convertible to gptq_marlin during runtime. Using gptq_marlin kernel.
2024-07-19 09:09:33,818 vllm.engine.llm_engine 968639 INFO     Initializing an LLM engine (v0.5.1) with config: model='/home/gx01/models/Qwen2-72B-Instruct-GPTQ-Int4', speculative_config=None, tokenizer='/home/gx01/models/Qwen2-72B-Instruct-GPTQ-Int4', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=gptq_marlin, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=0, served_model_name=/home/gx01/models/Qwen2-72B-Instruct-GPTQ-Int4, use_v2_block_manager=False, enable_prefix_caching=False)
2024-07-19 09:09:33,826 transformers.tokenization_utils_base 968639 INFO     loading file vocab.json
2024-07-19 09:09:33,826 transformers.tokenization_utils_base 968639 INFO     loading file merges.txt
2024-07-19 09:09:33,826 transformers.tokenization_utils_base 968639 INFO     loading file tokenizer.json
2024-07-19 09:09:33,827 transformers.tokenization_utils_base 968639 INFO     loading file added_tokens.json
2024-07-19 09:09:33,827 transformers.tokenization_utils_base 968639 INFO     loading file special_tokens_map.json
2024-07-19 09:09:33,827 transformers.tokenization_utils_base 968639 INFO     loading file tokenizer_config.json
2024-07-19 09:09:34,046 transformers.tokenization_utils_base 968639 WARNING  Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
2024-07-19 09:09:34,062 transformers.generation.configuration_utils 968639 INFO     loading configuration file /home/gx01/models/Qwen2-72B-Instruct-GPTQ-Int4/generation_config.json
2024-07-19 09:09:34,063 transformers.generation.configuration_utils 968639 INFO     Generate config GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": [
    151645,
    151643
  ],
  "pad_token_id": 151643,
  "repetition_penalty": 1.05,
  "temperature": 0.7,
  "top_k": 20,
  "top_p": 0.8
}

2024-07-19 09:09:34,285 vllm.distributed.parallel_state 968639 DEBUG    world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.4.129.234:42483 backend=nccl
2024-07-19 09:09:41,067 vllm.worker.model_runner 968639 INFO     Loading model weights took 38.5585 GB
2024-07-19 09:09:48,451 vllm.executor.gpu_executor 968639 INFO     # GPU blocks: 420, # CPU blocks: 819
2024-07-19 09:09:51,926 vllm.worker.model_runner 968639 INFO     Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
2024-07-19 09:09:51,927 vllm.worker.model_runner 968639 INFO     CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
2024-07-19 09:10:15,581 vllm.worker.model_runner 968639 INFO     Graph capturing finished in 24 secs.
2024-07-19 09:10:15,592 xinference.core.worker 164311 DEBUG    Leave launch_builtin_model, elapsed time: 45 s
2024-07-19 09:10:15,593 uvicorn.access 164241 INFO     10.4.134.25:12124 - "POST /v1/models HTTP/1.1" 200
2024-07-19 09:10:15,617 xinference.core.supervisor 164311 DEBUG    Enter list_models, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fa6360afa10>,), kwargs: {}
2024-07-19 09:10:15,618 xinference.core.worker 164311 DEBUG    Enter list_models, args: (<xinference.core.worker.WorkerActor object at 0x7fa56b519490>,), kwargs: {}
2024-07-19 09:10:15,618 xinference.core.worker 164311 DEBUG    Leave list_models, elapsed time: 0 s
2024-07-19 09:10:15,618 xinference.core.supervisor 164311 DEBUG    Leave list_models, elapsed time: 0 s
2024-07-19 09:10:15,619 uvicorn.access 164241 INFO     10.4.134.25:12124 - "GET /v1/models HTTP/1.1" 200
```

### Expected behavior / 期待表现

期望能给出问题排查方法
Hope to give the troubleshooting method

**Comment by qinxuye** [comment]
Remote server closed 一般是由于 OOM 导致的。

**Comment by JinCheng666** [comment]
> OOM

多谢。之前遇到vllm无法多卡推理的问题，该怎么排查问题？单卡是可以正常运行的。无法多卡运行，导致了OOM的问题

###多卡运行报错：
xoscar.errors.ServerClosed: [address=0.0.0.0:19877, pid=164311] Remote server unixsocket:///172292571136 closed

#### 详细报错
```bash
2024-07-19 10:48:32,508 uvicorn.access 164241 INFO     10.4.134.25:14935 - "GET /v1/engines/qwen%3A72b HTTP/1.1" 200
2024-07-19 10:48:37,487 xinference.core.supervisor 164311 DEBUG    Enter launch_builtin_model, model_uid: qwen:72b, model_name: qwen:72b, model_size: 72, model_format: gptq, quantization: Int4, replica: 1, kwargs: {}
2024-07-19 10:48:37,488 xinference.core.worker 164311 DEBUG    Enter get_model_count, args: (<xinference.core.worker.WorkerActor object at 0x7fa56b519490>,), kwargs: {}
2024-07-19 10:48:37,488 xinference.core.worker 164311 DEBUG    Leave get_model_count, elapsed time: 0 s
2024-07-19 10:48:37,488 xinference.core.worker 164311 DEBUG    Enter launch_builtin_model, args: (<xinference.core.worker.WorkerActor object at 0x7fa56b519490>,), kwargs: {'model_uid': 'qwen:72b-1-0', 'model_name': 'qwen:72b', 'model_size_in_billions': 72, 'model_format': 'gptq', 'quantization': 'Int4', 'model_engine': 'vLLM', 'model_type': 'LLM', 'n_gpu': 2, 'request_limits': None, 'peft_model_config': None, 'gpu_idx': None, 'download_hub': None}
2024-07-19 10:48:37,488 xinference.core.worker 164311 DEBUG    GPU selected: [0, 1] for model qwen:72b-1-0
2024-07-19 10:48:41,223 xinference.model.llm.core 164311 DEBUG    Launching qwen:72b-1-0 with VLLMChatModel
2024-07-19 10:48:41,224 xinference.model.llm.llm_family 164311 INFO     Caching from URI: /home/gx01/models/Qwen2-72B-Instruct-GPTQ-Int4
2024-07-19 10:48:41,224 xinference.model.llm.llm_family 164311 INFO     Cache /home/gx01/models/Qwen2-72B-Instruct-GPTQ-Int4 exists
2024-07-19 10:48:41,241 xinference.model.llm.vllm.core 983785 INFO     Loading qwen:72b with following model config: {'tokenizer_mode': 'auto', 'trust_remote_code': True, 'tensor_parallel_size': 2, 'block_size': 16, 'swap_space': 4, 'gpu_memory_utilization': 0.9, 'max_num_seqs': 256, 'quantization': None, 'max_model_len': 4096}Enable lora: False. Lora count: 0.
2024-07-19 10:48:41,243 transformers.configuration_utils 983785 INFO     loading configuration file /home/gx01/models/Qwen2-72B-Instruct-GPTQ-Int4/config.json
2024-07-19 10:48:41,244 transformers.configuration_utils 983785 INFO     Model config Qwen2Config {
  "_name_or_path": "/home/gx01/models/Qwen2-72B-Instruct-GPTQ-Int4",
  "architectures": [
    "Qwen2ForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 8192,
  "initializer_range": 0.02,
  "intermediate_size": 29696,
  "max_position_embeddings": 32768,
  "max_window_layers": 70,
  "model_type": "qwen2",
  "num_attention_heads": 64,
  "num_hidden_layers": 80,
  "num_key_value_heads": 8,
  "quantization_config": {
    "batch_size": 1,
    "bits": 4,
    "block_name_to_quantize": null,
    "cache_block_outputs": true,
    "damp_percent": 0.01,
    "dataset": null,
    "desc_act": false,
    "exllama_config": {
      "version": 1
    },
    "group_size": 128,
    "max_input_length": null,
    "model_seqlen": null,
    "module_name_preceding_first_block": null,
    "modules_in_block_to_quantize": null,
    "pad_token_id": null,
    "quant_method": "gptq",
    "sym": true,
    "tokenizer": null,
    "true_sequential": true,
    "use_cuda_fp16": false,
    "use_exllama": true
  },
  "rms_norm_eps": 1e-06,
  "rope_theta": 1000000.0,
  "sliding_window": 131072,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.42.4",
  "use_cache": true,
  "use_sliding_window": false,
  "vocab_size": 152064
}

2024-07-19 10:48:41,252 vllm.model_executor.layers.quantization.gptq_marlin 983785 INFO     The model is convertible to gptq_marlin during runtime. Using gptq_marlin kernel.
2024-07-19 10:48:41,265 vllm.config  983785 INFO     Defaulting to use mp for distributed inference
2024-07-19 10:48:41,267 vllm.engine.llm_engine 983785 INFO     Initializing an LLM engine (v0.5.1) with config: model='/home/gx01/models/Qwen2-72B-Instruct-GPTQ-Int4', speculative_config=None, tokenizer='/home/gx01/models/Qwen2-72B-Instruct-GPTQ-Int4', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=gptq_marlin, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=0, served_model_name=/home/gx01/models/Qwen2-72B-Instruct-GPTQ-Int4, use_v2_block_manager=False, enable_prefix_caching=False)
2024-07-19 10:48:41,276 transformers.tokenization_utils_base 983785 INFO     loading file vocab.json
2024-07-19 10:48:41,276 transformers.tokenization_utils_base 983785 INFO     loading file merges.txt
2024-07-19 10:48:41,276 transformers.tokenization_utils_base 983785 INFO     loading file tokenizer.json
2024-07-19 10:48:41,276 transformers.tokenization_utils_base 983785 INFO     loading file added_tokens.json
2024-07-19 10:48:41,276 transformers.tokenization_utils_base 983785 INFO     loading file special_tokens_map.json
2024-07-19 10:48:41,276 transformers.tokenization_utils_base 983785 INFO     loading file tokenizer_config.json
2024-07-19 10:48:41,499 transformers.tokenization_utils_base 983785 WARNING  Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
2024-07-19 10:48:41,516 transformers.generation.configuration_utils 983785 INFO     loading configuration file /home/gx01/models/Qwen2-72B-Instruct-GPTQ-Int4/generation_config.json
2024-07-19 10:48:41,516 transformers.generation.configuration_utils 983785 INFO     Generate config GenerationConfig {
  "bos_token_id": 151643,
  "do_sample": true,
  "eos_token_id": [
    151645,
    151643
  ],
  "pad_token_id": 151643,
  "repetition_penalty": 1.05,
  "temperature": 0.7,
  "top_k": 20,
  "top_p": 0.8
}

2024-07-19 10:48:41,710 vllm.executor.multiproc_worker_utils 983929 INFO     Worker ready; awaiting tasks
2024-07-19 10:48:41,786 vllm.distributed.parallel_state 983785 DEBUG    world_size=2 rank=0 local_rank=0 distributed_init_method=tcp://127.0.0.1:51963 backend=nccl
2024-07-19 10:48:42,051 vllm.distributed.parallel_state 983929 DEBUG    world_size=2 rank=1 local_rank=1 distributed_init_method=tcp://127.0.0.1:51963 backend=nccl
2024-07-19 10:48:42,066 vllm.utils   983785 INFO     Found nccl from library libnccl.so.2
2024-07-19 10:48:42,066 vllm.utils   983929 INFO     Found nccl from library libnccl.so.2
2024-07-19 10:48:42,067 vllm.distributed.device_communicators.pynccl 983929 INFO     vLLM is using nccl==2.20.5
2024-07-19 10:48:42,067 vllm.distributed.device_communicators.pynccl 983785 INFO     vLLM is using nccl==2.20.5
2024-07-19 10:48:42,306 vllm.distributed.device_communicators.custom_all_reduce_utils 983785 INFO     reading GPU P2P access cache from /home/gx01/.config/vllm/gpu_p2p_access_cache_for_0,1.json
2024-07-19 10:48:42,306 vllm.distributed.device_communicators.custom_all_reduce_utils 983929 INFO     reading GPU P2P access cache from /home/gx01/.config/vllm/gpu_p2p_access_cache_for_0,1.json
2024-07-19 10:48:42,549 xinference.core.worker 164311 ERROR    Failed to load model qwen:72b-1-0
Traceback (most recent call last):
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xinference/core/worker.py", line 841, in launch_builtin_model
    await model_ref.load()
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 230, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server unixsocket:///172292571136 closed
2024-07-19 10:48:42,567 xinference.core.supervisor 164311 DEBUG    Enter terminate_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fa6360afa10>, 'qwen:72b'), kwargs: {'suppress_exception': True}
2024-07-19 10:48:42,567 xinference.core.supervisor 164311 DEBUG    Leave terminate_model, elapsed time: 0 s
2024-07-19 10:48:42,570 xinference.api.restful_api 164241 ERROR    [address=0.0.0.0:19877, pid=164311] Remote server unixsocket:///172292571136 closed
Traceback (most recent call last):
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xinference/api/restful_api.py", line 835, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xinference/core/supervisor.py", line 988, in launch_builtin_model
    await _launch_model()
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xinference/core/supervisor.py", line 952, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xinference/core/supervisor.py", line 932, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xinference/core/worker.py", line 841, in launch_builtin_model
    await model_ref.load()
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 230, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/gx01/miniconda3/envs/inference0.13.1/lib/python3.10/site-packages/xoscar/backends/core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: [address=0.0.0.0:19877, pid=164311] Remote server unixsocket:///172292571136 closed
2024-07-19 10:48:42,571 uvicorn.access 164241 INFO     10.4.134.25:14935 - "POST /v1/models HTTP/1.1" 500
```

**Comment by qinxuye** [comment]
单卡和多卡不是一个模型吧？

**Comment by JinCheng666** [comment]
> 单卡和多卡不是一个模型吧？

@qinxuye 
是一个模型，都是qwen2:72b-gptq-int4
之前一直都可以双卡运行的，某天机器重启了一次，之后就无法双卡运行，报错如上。只能单卡运行了。
核心就是这个报错：
xoscar.errors.ServerClosed: [address=0.0.0.0:19877, pid=164311] Remote server unixsocket:///172292571136 closed

**Comment by zxr-Cr7** [comment]
请问具体解决办法是什么/我的错误也是这个
