### ISSUE TITLE
Failed to import from vllm._C with ImportError('libcuda.so.1: cannot open shared object file: No such file or directory') 或者 Failed to import from vllm._C with ImportError('libcuda.so.1: cannot open shared object file: No such file or directory')

### ISSUE THREAD

**Issue by Weishaoya** [xorbitsai/inference#2604]
### System Info / 系統信息

ubuntu 22.04
cuda:12.4.1
![image](https://github.com/user-attachments/assets/40fb65a3-6903-4821-8ed6-001a8a5ac9ab)

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

docker version: latest

### The command used to start Xinference / 用以启动 xinference 的命令

docker run \
  -v /home/lw/.xinference:/root/.xinference \
  -v /home/lw/.cache/huggingface:/root/.cache/huggingface \
  -v /home/lw/.cache/modelscope:/root/.cache/modelscope \
  -v /home/lw/models/Qwen2_5-14B-Instruct:/home/lw/models/Qwen2_5-14B-Instruct \
  -p 10860:9997 \
   dc3c46bccde1 \
  xinference-local -H 0.0.0.0

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/9f61dc15-4e74-44d4-aaea-162daf7bb05a)
![image](https://github.com/user-attachments/assets/1cc07e25-80ed-495f-9506-dfa4b6204a71)

### Expected behavior / 期待表现

急，有临时方案吗，谢谢！

**Comment by Weishaoya** [comment]
docker run --name xinference -d -p 10860:9997 -e XINFERENCE_HOME=/data \
-v /home/lw/programs/xinference_docker/data:/data \
--gpus all \
registry.cn-hangzhou.aliyuncs.com/xprobe_xinference/xinference:latest \
xinference-local -H 0.0.0.0

已解决，这个命令启动似乎更好

**Comment by xiyuan-lee** [comment]
是因为没有加--gpus？

**Comment by Weishaoya** [comment]
> 是因为没有加--gpus？

是的，cuda版本要升级到12.4，nvidia docker工具包也要安装好
