### ISSUE TITLE
Xinference_v1.3.1版本回退到v1.2.1版本会报错

### ISSUE THREAD

**Issue by gxhperson** [xorbitsai/inference#3130]
### System Info / 系統信息

CUDA=12.6   GPU=英伟达A10 或者英伟达L20 

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [x] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

Xinference_v1.3.1   v1.2.1

### The command used to start Xinference / 用以启动 xinference 的命令

docker run -d -e NCCL_IB_DISABLE=1 -e NCCL_P2P_DISABLE=1 --shm-size=80g -v /data/xinference_models:/xinference_models -e XINFERENCE_HOME=/xinference_models -p 9998:9997 --gpus all xprobe/xinference:v1.3.1 xinference-local -H 0.0.0.0

### Reproduction / 复现过程

Xinference_v1.3.1版本回退到v1.2.1版本会报错
1.使用Xinference_v1.3.1正常启动模型之后，停止并删除v1.3.1容器
2.启动v1.2.1容器，启动同一个模型

### Expected behavior / 期待表现

Xinference_v1.3.1版本回退到v1.2.1版本会报错，猜测是因为启动了高版本之后，修改启动模型的缓存内容导致重新启动低版本镜像时，低版本镜像没有n_worker这个参数导致，如果想要不报错，我该清理什么东西

<img width="481" alt="Image" src="https://github.com/user-attachments/assets/6b856cc5-009e-4be7-b84c-c109cf6d843f" />

**Comment by qinxuye** [comment]
<img width="645" alt="Image" src="https://github.com/user-attachments/assets/8c754257-0c58-410d-9daf-4b5b682b6c7f" />

可以点击叉清理加载参数缓存。

**Comment by gxhperson** [comment]
点×之后问题仍然存在，并且在右侧复制按钮可以看到明显的 n_worker 1 的参数

![Image](https://github.com/user-attachments/assets/65fc7e5e-841e-4bcf-8984-7524ce72180b)

![Image](https://github.com/user-attachments/assets/d8fa917f-e1a3-410c-974e-4c3fd9aecdb1)

**Comment by qinxuye** [comment]
那可能要清除缓存了。

@yiboyasss 看下这种情况下，是不是 config 的清除没有清理干净。

**Comment by gxhperson** [comment]
问题已解决.原因：浏览器缓存，回退版本后，打开Xinference前端，页面是前端是高版本前端，需要深度清理浏览器缓存之后重新打开浏览器进入不会报错n_worker错误

**Comment by gxhperson** [comment]
原因：浏览器缓存，回退版本后，打开Xinference前端，前端仍是高版本前端，需要深度清理浏览器缓存之后重新打开浏览器进入不会报错n_worker错误
