### ISSUE TITLE
The latest docker image does not support 5090D?

### ISSUE THREAD

**Issue by Simonqujian78** [xorbitsai/inference#3682]
### System Info / 系統信息

CUDA 12.8
Pytorch : nightly 
5090D+win11

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [x] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

v1.7.0.post1

### The command used to start Xinference / 用以启动 xinference 的命令

Run reranker model

### Reproduction / 复现过程

Run reranker model qwen3 reranker, error information 
Server error: 503 - [address=0.0.0.0:41371, pid=279] CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1 Compile with TORCH_USE_CUDA_DSA to enable device-side assertions.

### Expected behavior / 期待表现

Compatible with 50 Serials

**Comment by qinxuye** [comment]
We are building cuda 12.8 docker to support 50 series.

**Comment by Simonqujian78** [comment]
> We are building cuda 12.8 docker to support 50 series.

Great！

**Comment by Simonqujian78** [comment]
> We are building cuda 12.8 docker to support 50 series.

Hello,whether  the new version 1.7.1 docker image support 50 series?

**Comment by qinxuye** [comment]
> > We are building cuda 12.8 docker to support 50 series.
> 
> Hello,whether the new version 1.7.1 docker image support 50 series?

Not yet, we are testing new cuda 12.8 based images.

**Comment by Simonqujian78** [comment]
> This issue is stale because it has been open for 7 days with no activity.

Itis  not  resolved till today.

**Comment by Simonqujian78** [comment]
> > > We are building cuda 12.8 docker to support 50 series.
> > 
> > Hello,whether the new version 1.7.1 docker image support 50 series?
> 
> Not yet, we are testing new cuda 12.8 based images.

Whether the problem is resolved？

**Comment by Simonqujian78** [comment]
> > > We are building cuda 12.8 docker to support 50 series.
> > 
> > Hello,whether the new version 1.7.1 docker image support 50 series?
> 
> Not yet, we are testing new cuda 12.8 based images.

Hello，is there any update information  on docker support  50serials?

**Comment by qinxuye** [comment]
We will push cuda 12.8 docker image this week.

**Comment by Simonqujian78** [comment]
> We will push cuda 12.8 docker image this week.
Great!
