### ISSUE TITLE
Qwen3-Reranker-4B使用报错

### ISSUE THREAD

**Issue by three-leg0cat** [xorbitsai/inference#3710]
### System Info / 系統信息

docker镜像v1.7.0.post1

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [x] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

v1.7.0.post1

### The command used to start Xinference / 用以启动 xinference 的命令

![Image](https://github.com/user-attachments/assets/a64036c1-2d18-4ea3-a79b-3490bf3a8195)

### Reproduction / 复现过程

2025-06-24 23:43:36,902 xinference.core.model 5892 ERROR    Model actor is out of memory, model id: Qwen3-Reranker-4B-0, error: CUDA out of memory. Tried to allocate 1.98 GiB. GPU 0 has a total capacity of 22.07 GiB of which 899.44 MiB is free. Including non-PyTorch memory, this process has 5.14 GiB memory in use. Of the allocated memory 4.87 GiB is allocated by PyTorch, and 17.85 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/opt/inference/xinference/core/model.py", line 147, in _async_wrapper
    return await fn(self, *args, **kwargs)
  File "/opt/inference/xinference/core/model.py", line 697, in _call_wrapper
    ret = await asyncio.to_thread(fn, *args, **kwargs)
  File "/usr/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/inference/xinference/model/rerank/core.py", line 377, in rerank
    similarity_scores = self.compute_logits(inputs)
  File "/opt/inference/xinference/model/rerank/core.py", line 295, in compute_logits
    batch_scores = model(**inputs).logits[:, -1, :]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py", line 969, in wrapper
    output = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen3/modeling_qwen3.py", line 730, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/inference/xinference/model/rerank/core.py", line 136, in forward
    return self.model(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py", line 969, in wrapper
    output = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen3/modeling_qwen3.py", line 432, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/sparse.py", line 190, in forward
    return F.embedding(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/functional.py", line 2551, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.98 GiB. GPU 0 has a total capacity of 22.07 GiB of which 899.44 MiB is free. Including non-PyTorch memory, this process has 5.14 GiB memory in use. Of the allocated memory 4.87 GiB is allocated by PyTorch, and 17.85 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
2025-06-24 23:43:36,948 xinference.core.supervisor 79 DEBUG    [request b8b45240-518f-11f0-9684-0242ac110004] Enter get_model_status, args: <xinference.core.supervisor.SupervisorActor object at 0x7fb39de5f790>,Qwen3-Reranker-4B-0, kwargs:
2025-06-24 23:43:36,948 xinference.core.supervisor 79 DEBUG    [request b8b45240-518f-11f0-9684-0242ac110004] Leave get_model_status, elapsed time: 0 s
2025-06-24 23:43:36,949 xinference.api.restful_api 1 ERROR    Model actor is out of memory, model id: Qwen3-Reranker-4B-0, error: CUDA out of memory. Tried to allocate 1.98 GiB. GPU 0 has a total capacity of 22.07 GiB of which 899.44 MiB is free. Including non-PyTorch memory, this process has 5.14 GiB memory in use. Of the allocated memory 4.87 GiB is allocated by PyTorch, and 17.85 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/api/restful_api.py", line 1498, in rerank
    scores = await model.rerank(
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 261, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 124, in _wait
    return await future
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/core.py", line 104, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 0.0.0.0:43805 closed: 0 bytes read on a total of 11 expected bytes
2025-06-24 23:43:37,025 xinference.core.model 6041 ERROR    Model actor is out of memory, model id: Qwen3-Reranker-4B-1, error: CUDA out of memory. Tried to allocate 1.98 GiB. GPU 0 has a total capacity of 22.07 GiB of which 1.67 GiB is free. Including non-PyTorch memory, this process has 20.38 GiB memory in use. Of the allocated memory 19.41 GiB is allocated by PyTorch, and 719.81 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/opt/inference/xinference/core/model.py", line 147, in _async_wrapper
    return await fn(self, *args, **kwargs)
  File "/opt/inference/xinference/core/model.py", line 697, in _call_wrapper
    ret = await asyncio.to_thread(fn, *args, **kwargs)
  File "/usr/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/inference/xinference/model/rerank/core.py", line 377, in rerank
    similarity_scores = self.compute_logits(inputs)
  File "/opt/inference/xinference/model/rerank/core.py", line 295, in compute_logits
    batch_scores = model(**inputs).logits[:, -1, :]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py", line 969, in wrapper
    output = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen3/modeling_qwen3.py", line 730, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/inference/xinference/model/rerank/core.py", line 136, in forward
    return self.model(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py", line 969, in wrapper
    output = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen3/modeling_qwen3.py", line 463, in forward
    layer_outputs = decoder_layer(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_layers.py", line 48, in __call__
    return super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen3/modeling_qwen3.py", line 281, in forward
    hidden_states = self.input_layernorm(hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen3/modeling_qwen3.py", line 72, in forward
    return self.weight * hidden_states.to(input_dtype)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.98 GiB. GPU 0 has a total capacity of 22.07 GiB of which 1.67 GiB is free. Including non-PyTorch memory, this process has 20.38 GiB memory in use. Of the allocated memory 19.41 GiB is allocated by PyTorch, and 719.81 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
2025-06-24 23:43:37,049 xinference.core.supervisor 79 DEBUG    [request b8c3be92-518f-11f0-9684-0242ac110004] Enter get_model_status, args: <xinference.core.supervisor.SupervisorActor object at 0x7fb39de5f790>,Qwen3-Reranker-4B-1, kwargs:
2025-06-24 23:43:37,049 xinference.core.supervisor 79 DEBUG    [request b8c3be92-518f-11f0-9684-0242ac110004] Leave get_model_status, elapsed time: 0 s
2025-06-24 23:43:37,050 xinference.api.restful_api 1 ERROR    Model actor is out of memory, model id: Qwen3-Reranker-4B-1, error: CUDA out of memory. Tried to allocate 1.98 GiB. GPU 0 has a total capacity of 22.07 GiB of which 1.67 GiB is free. Including non-PyTorch memory, this process has 20.38 GiB memory in use. Of the allocated memory 19.41 GiB is allocated by PyTorch, and 719.81 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/api/restful_api.py", line 1498, in rerank
    scores = await model.rerank(
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 261, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 124, in _wait
    return await future
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/core.py", line 104, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 0.0.0.0:34837 closed: 0 bytes read on a total of 11 expected bytes

### Expected behavior / 期待表现

配置了replica 2，模型成功在两张A10卡上运行，但使用时仍会报单张卡显存不足的错误。
希望两张卡并行计算，解决单卡资源不足的限制。

**Comment by qinxuye** [comment]
使用两张卡推一个模型是指定 n-gpu，replica 是用来指定有2个一样的实例。

**Comment by 3leg0ocat** [comment]
> 使用两张卡推一个模型是指定 n-gpu，replica 是用来指定有2个一样的实例。

请问用web界面起模型的话，这个参数是在哪里指定？

**Comment by qinxuye** [comment]
<img width="290" alt="Image" src="https://github.com/user-attachments/assets/66675309-14ad-4ff7-bc57-83ca305617a4" />

指定 2 试下。

**Comment by 3leg0ocat** [comment]
> <img alt="Image" width="290" src="https://private-user-images.githubusercontent.com/357506/459305732-66675309-14ad-4ff7-bc57-83ca305617a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTA5MjY4ODcsIm5iZiI6MTc1MDkyNjU4NywicGF0aCI6Ii8zNTc1MDYvNDU5MzA1NzMyLTY2Njc1MzA5LTE0YWQtNGZmNy1iYzU3LTgzY2EzMDU2MTdhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDYyNlQwODI5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjc0N2E1ZmE4ZDYwZWQ4NGVhM2ZkYTA0ZGU0OTM5MzMyNjQzYWEwYTkzOWNhZDI3MTk1MjY3OTkyMzA0MTIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0_hMTZNfKbIsA_03rhoR41bJdBkBdyIcWPfo-CTfjs0">
> 指定 2 试下。

rerank模型启动页面没有这个参数，只有语言模型里才有。直接在这里加n-gpu参数能生效吗？

![Image](https://github.com/user-attachments/assets/bc7ab4ec-a408-43b4-aa74-05922393f289)

**Comment by qinxuye** [comment]
哦哦，你可能要试下用命令加载 --n-gpu 2。右上角可以拷贝当前参数，可以加在后面。

**Comment by 3leg0ocat** [comment]
> 哦哦，你可能要试下用命令加载 --n-gpu 2。右上角可以拷贝当前参数，可以加在后面。

好的。谢谢。

**Comment by 3leg0ocat** [comment]
> 哦哦，你可能要试下用命令加载 --n-gpu 2。右上角可以拷贝当前参数，可以加在后面。

指定了参数模型确实能在多张卡上跑，但使用时还是报错。请问我并没有指定GPU 0的索引，甚至指定了四张卡，为什么还会爆0号卡显存不足的错误？0号卡上是embedding模型，是可以正常使用的。


2025-06-24 22:59:01,780 xinference.core.model 1639 ERROR    Model actor is out of memory, model id: Qwen3-Reranker-4B-0, error: CUDA out of memory. Tried to allocate 1.98 GiB. GPU 0 has a total capacity of 22.07 GiB of which 1.66 GiB is free. Including non-PyTorch memory, this process has 20.39 GiB memory in use. Of the allocated memory 19.41 GiB is allocated by PyTorch, and 712.21 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/opt/inference/xinference/core/model.py", line 147, in _async_wrapper
    return await fn(self, *args, **kwargs)
  File "/opt/inference/xinference/core/model.py", line 697, in _call_wrapper
    ret = await asyncio.to_thread(fn, *args, **kwargs)
  File "/usr/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/inference/xinference/model/rerank/core.py", line 377, in rerank
    similarity_scores = self.compute_logits(inputs)
  File "/opt/inference/xinference/model/rerank/core.py", line 295, in compute_logits
    batch_scores = model(**inputs).logits[:, -1, :]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py", line 969, in wrapper
    output = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen3/modeling_qwen3.py", line 730, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/inference/xinference/model/rerank/core.py", line 136, in forward
    return self.model(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py", line 969, in wrapper
    output = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen3/modeling_qwen3.py", line 463, in forward
    layer_outputs = decoder_layer(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_layers.py", line 48, in __call__
    return super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen3/modeling_qwen3.py", line 281, in forward
    hidden_states = self.input_layernorm(hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen3/modeling_qwen3.py", line 72, in forward
    return self.weight * hidden_states.to(input_dtype)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.98 GiB. GPU 0 has a total capacity of 22.07 GiB of which 1.66 GiB is free. Including non-PyTorch memory, this process has 20.39 GiB memory in use. Of the allocated memory 19.41 GiB is allocated by PyTorch, and 712.21 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
2025-06-24 22:59:01,819 xinference.model.rerank.core 1639 INFO     Rerank with kwargs: {}, model: Qwen3ForCausalLM(
  (model): _ModelWrapper(
    (model): Qwen3Model(
      (embed_tokens): Embedding(151669, 2560)
      (layers): ModuleList(
        (0-35): 36 x Qwen3DecoderLayer(
          (self_attn): Qwen3Attention(
            (q_proj): Linear(in_features=2560, out_features=4096, bias=False)
            (k_proj): Linear(in_features=2560, out_features=1024, bias=False)
            (v_proj): Linear(in_features=2560, out_features=1024, bias=False)
            (o_proj): Linear(in_features=4096, out_features=2560, bias=False)
            (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
            (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          )
          (mlp): Qwen3MLP(
            (gate_proj): Linear(in_features=2560, out_features=9728, bias=False)
            (up_proj): Linear(in_features=2560, out_features=9728, bias=False)
            (down_proj): Linear(in_features=9728, out_features=2560, bias=False)
            (act_fn): SiLU()
          )
          (input_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
          (post_attention_layernorm): Qwen3RMSNorm((2560,), eps=1e-06)
        )
      )
      (norm): Qwen3RMSNorm((2560,), eps=1e-06)
      (rotary_emb): Qwen3RotaryEmbedding()
    )
  )
  (lm_head): Linear(in_features=2560, out_features=151669, bias=False)
)
2025-06-24 22:59:01,834 xinference.core.supervisor 79 DEBUG    [request 7e3651c8-5189-11f0-9684-0242ac110004] Enter get_model_status, args: <xinference.core.supervisor.SupervisorActor object at 0x7fb39de5f790>,Qwen3-Reranker-4B-0, kwargs:
2025-06-24 22:59:01,834 xinference.core.supervisor 79 DEBUG    [request 7e3666fe-5189-11f0-9684-0242ac110004] Enter get_model_status, args: <xinference.core.supervisor.SupervisorActor object at 0x7fb39de5f790>,Qwen3-Reranker-4B-0, kwargs:
2025-06-24 22:59:01,835 xinference.core.supervisor 79 DEBUG    [request 7e3651c8-5189-11f0-9684-0242ac110004] Leave get_model_status, elapsed time: 0 s
2025-06-24 22:59:01,835 xinference.core.supervisor 79 DEBUG    [request 7e3666fe-5189-11f0-9684-0242ac110004] Leave get_model_status, elapsed time: 0 s
2025-06-24 22:59:01,836 xinference.api.restful_api 1 ERROR    Model actor is out of memory, model id: Qwen3-Reranker-4B-0, error: CUDA out of memory. Tried to allocate 1.98 GiB. GPU 0 has a total capacity of 22.07 GiB of which 1.66 GiB is free. Including non-PyTorch memory, this process has 20.39 GiB memory in use. Of the allocated memory 19.41 GiB is allocated by PyTorch, and 712.21 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/api/restful_api.py", line 1498, in rerank
    scores = await model.rerank(
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 261, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 124, in _wait
    return await future
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/core.py", line 104, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 0.0.0.0:46213 closed: 0 bytes read on a total of 11 expected bytes
2025-06-24 22:59:01,838 xinference.api.restful_api 1 ERROR    Model actor is out of memory, model id: Qwen3-Reranker-4B-0, error: CUDA out of memory. Tried to allocate 1.98 GiB. GPU 0 has a total capacity of 22.07 GiB of which 1.66 GiB is free. Including non-PyTorch memory, this process has 20.39 GiB memory in use. Of the allocated memory 19.41 GiB is allocated by PyTorch, and 712.21 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/api/restful_api.py", line 1498, in rerank
    scores = await model.rerank(
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 261, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 124, in _wait
    return await future
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/core.py", line 104, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 0.0.0.0:46213 closed: 0 bytes read on a total of 11 expected bytes
2025-06-24 22:59:02,437 xinference.core.worker 79 WARNING  Process 0.0.0.0:46213 is down.
2025-06-24 22:59:02,440 xinference.core.worker 79 INFO     [request 7e92c110-5189-11f0-9684-0242ac110004] Enter terminate_model, args: <xinference.core.worker.WorkerActor object at 0x7fb3c16afbf0>,Qwen3-Reranker-4B-0, kwargs: is_model_die=True
2025-06-24 22:59:02,441 xinference.core.worker 79 DEBUG    Fail to get pool addresses, error: [Errno 111] Connection refused
2025-06-24 22:59:02,441 xinference.core.worker 79 DEBUG    Start to destroy model actor: ActorRef(uid=b'Qwen3-Reranker-4B-0', address='0.0.0.0:46213')
2025-06-24 22:59:02,441 xinference.core.worker 79 DEBUG    Destroy model actor failed, model uid: Qwen3-Reranker-4B-0, error: [Errno 111] Connection refused
2025-06-24 22:59:02,441 xinference.core.worker 79 DEBUG    Remove sub pools: ['0.0.0.0:46213']
2025-06-24 22:59:02,441 xinference.core.worker 79 DEBUG    Remove sub pool failed, model uid: Qwen3-Reranker-4B-0, error: '0.0.0.0:46213'
2025-06-24 22:59:02,442 xinference.core.worker 79 INFO     [request 7e92c110-5189-11f0-9684-0242ac110004] Leave terminate_model, elapsed time: 0 s
2025-06-24 22:59:02,442 xinference.core.worker 79 WARNING  Recreating model actor Qwen3-Reranker-4B-0 ...
2025-06-24 22:59:02,442 xinference.core.worker 79 INFO     [request 7e931f3e-5189-11f0-9684-0242ac110004] Enter launch_builtin_model, args: <xinference.core.worker.WorkerActor object at 0x7fb3c16afbf0>, kwargs: model_uid=Qwen3-Reranker-4B-0,model_name=Qwen3-Reranker-4B,model_size_in_billions=None,model_format=None,quantization=None,model_engine=None,model_type=rerank,n_gpu=auto,n_worker=1,shard=0,driver_info=None,peft_model_config=None,request_limits=None,gpu_idx=[2],download_hub=None,model_path=/app/model/Qwen3-Reranker-4B,xavier_config=None

**Comment by dengcao** [comment]
以下是通过vllm快捷安装Qwen3-Embedding-0.6B/4B/8B，Qwen3-Reranker-0.6B/4B/8B的办法。

Docker 快速部署（一键安装包）：
Docker Compose Quick Installation:

Hugging Face：
https://huggingface.co/dengcao/Qwen3-Embedding-0.6B
https://huggingface.co/dengcao/Qwen3-Embedding-4B
https://huggingface.co/dengcao/Qwen3-Embedding-8B
https://huggingface.co/dengcao/Qwen3-Reranker-0.6B
https://huggingface.co/dengcao/Qwen3-Reranker-4B
https://huggingface.co/dengcao/Qwen3-Reranker-8B

ModelScope：
https://www.modelscope.cn/models/dengcao/Qwen3-Embedding-0.6B
https://www.modelscope.cn/models/dengcao/Qwen3-Embedding-4B
https://www.modelscope.cn/models/dengcao/Qwen3-Embedding-8B
https://www.modelscope.cn/models/dengcao/Qwen3-Reranker-0.6B
https://www.modelscope.cn/models/dengcao/Qwen3-Reranker-4B
https://www.modelscope.cn/models/dengcao/Qwen3-Reranker-8B

**Comment by 3leg0ocat** [comment]
把0号卡空出来测试时，还是会报错，检查GPU实时占用并没有使用到0号卡的资源。

**Comment by qinxuye** [comment]
这个 GPU 0 不一定是指所有的里面的 0。

我们还没测试过多卡，晚点试下。

**Comment by 3leg0ocat** [comment]
> 这个 GPU 0 不一定是指所有的里面的 0。
> 
> 我们还没测试过多卡，晚点试下。

好的。谢谢。

**Comment by zhengf312** [comment]
mark
