### ISSUE TITLE
xllamacpp自从0.2.8后的版本whl仅提供cp310-abi3，就无法正常启动模型，用回cp310-cp310即可。

### ISSUE THREAD

**Issue by edward687** [xorbitsai/inference#4675]
### System Info / 系統信息

Cuda=12.8
xllamacpp=0.2.6到0.2.12
Python=3.10
OS=Ubuntu22.04
GPU=Tesla V100 sxm2 16G x2

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [x] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

v2.2.0

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 9990

### Reproduction / 复现过程

0.2.8-0.2.12均会出现：
common_init_from_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)
/home/runner/work/xllamacpp/xllamacpp/thirdparty/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:96: CUDA error
ggml_cuda_compute_forward: MUL_MAT failed
CUDA error: no kernel image is available for execution on the device
  current device: 0, in function ggml_cuda_compute_forward at /home/runner/work/xllamacpp/xllamacpp/thirdparty/llama.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:2751
  err

### Expected behavior / 期待表现

继续提供cp310-cp310的whl或者具体编译方法？

**Comment by qinxuye** [comment]
@codingl2k1 帮忙看下。

**Comment by codingl2k1** [comment]
我打了个 fix 的 wheel，你可以试试：https://github.com/xorbitsai/xllamacpp/actions/runs/23137778170/job/67205924894

<img width="905" height="653" alt="Image" src="https://github.com/user-attachments/assets/42ebfcac-a5b9-4d59-a873-6c4432d2a204" />

**Comment by codingl2k1** [comment]
Tested on V100:

<img width="1398" height="588" alt="Image" src="https://github.com/user-attachments/assets/986ebee7-c9fa-495b-a3f1-23a1bbaef29b" />

```python
 import xllamacpp as xlc
 from openai import OpenAI
 
 # Start server
 params = xlc.CommonParams()
 params.model.path = "/root/Qwen3.5-0.8B-Q4_K_M.gguf"
 server = xlc.Server(params)
 
 # Connect using OpenAI client
 client = OpenAI(
     base_url=server.listening_address + "/v1",
     api_key="not-required"  # No API key needed for local server
 )
 
 # Make chat completion request
 response = client.chat.completions.create(
     model="local-model",
     messages=[{"role": "user", "content": "What is the capital of France?"}],
     max_tokens=1000
 )
 
 print(response.choices[0].message.content, flush=True)
```

**Comment by edward687** [comment]
> Tested on V100:
> <img alt="Image" width="1398" height="588" src="https://private-user-images.githubusercontent.com/138426806/564122181-986ebee7-c9fa-495b-a3f1-23a1bbaef29b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzM2NzM0NjgsIm5iZiI6MTc3MzY3MzE2OCwicGF0aCI6Ii8xMzg0MjY4MDYvNTY0MTIyMTgxLTk4NmViZWU3LWM5ZmEtNDk1Yi1hM2YxLTIzYTFiYmFlZjI5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDMxNlQxNDU5MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZmY1MzQ1M2VkYTc2N2U5Nzk4ODliMzhmMTk3Y2M5MTgxOWZkM2I2ZDg0NjE1MDczMmFkYzE3ZDUzODliOTlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.G7cpnWFCPodivNIXBGGDN0JdSGv1WeD9BghOhk7IRpQ">
> 
>  import xllamacpp as xlc
>  from openai import OpenAI
>  
>  # Start server
>  params = xlc.CommonParams()
>  params.model.path = "/root/Qwen3.5-0.8B-Q4_K_M.gguf"
>  server = xlc.Server(params)
>  
>  # Connect using OpenAI client
>  client = OpenAI(
>      base_url=server.listening_address + "/v1",
>      api_key="not-required"  # No API key needed for local server
>  )
>  
>  # Make chat completion request
>  response = client.chat.completions.create(
>      model="local-model",
>      messages=[{"role": "user", "content": "What is the capital of France?"}],
>      max_tokens=1000
>  )
>  
>  print(response.choices[0].message.content, flush=True)

根据代码，可以正常启动并返回。但是Xin服务无法正常启动，换回0.2.7就可以。

**Comment by codingl2k1** [comment]
> > Tested on V100:
> > <img alt="Image" width="1398" height="588" src="https://private-user-images.githubusercontent.com/138426806/564122181-986ebee7-c9fa-495b-a3f1-23a1bbaef29b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzM2NzM0NjgsIm5iZiI6MTc3MzY3MzE2OCwicGF0aCI6Ii8xMzg0MjY4MDYvNTY0MTIyMTgxLTk4NmViZWU3LWM5ZmEtNDk1Yi1hM2YxLTIzYTFiYmFlZjI5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDMxNlQxNDU5MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZmY1MzQ1M2VkYTc2N2U5Nzk4ODliMzhmMTk3Y2M5MTgxOWZkM2I2ZDg0NjE1MDczMmFkYzE3ZDUzODliOTlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.G7cpnWFCPodivNIXBGGDN0JdSGv1WeD9BghOhk7IRpQ">
> > 
> >  import xllamacpp as xlc
> >  from openai import OpenAI
> >  
> >  # Start server
> >  params = xlc.CommonParams()
> >  params.model.path = "/root/Qwen3.5-0.8B-Q4_K_M.gguf"
> >  server = xlc.Server(params)
> >  
> >  # Connect using OpenAI client
> >  client = OpenAI(
> >      base_url=server.listening_address + "/v1",
> >      api_key="not-required"  # No API key needed for local server
> >  )
> >  
> >  # Make chat completion request
> >  response = client.chat.completions.create(
> >      model="local-model",
> >      messages=[{"role": "user", "content": "What is the capital of France?"}],
> >      max_tokens=1000
> >  )
> >  
> >  print(response.choices[0].message.content, flush=True)
> 
> 根据代码，可以正常启动并返回。但是Xin服务无法正常启动，换回0.2.7就可以。

有xinf的错误日志吗？

**Comment by edward687** [comment]
> > > Tested on V100:

> 有xinf的错误日志吗？

log文件无任何信息打印出来（删除过log后重启，仍然无任何打印信息），看status是看到已运行，但其实访问UI无任何反应。

**Comment by codingl2k1** [comment]
> > > > Tested on V100:
> 
> > 有xinf的错误日志吗？
> 
> log文件无任何信息打印出来（删除过log后重启，仍然无任何打印信息），看status是看到已运行，但其实访问UI无任何反应。

xinf你是用的啥版本？

**Comment by edward687** [comment]
> > > > > Tested on V100:
> > 
> > 
> > > 有xinf的错误日志吗？
> > 
> > 
> > log文件无任何信息打印出来（删除过log后重启，仍然无任何打印信息），看status是看到已运行，但其实访问UI无任何反应。
> 
> xinf你是用的啥版本？

顺手升级到2.3.0，安装回pynvml，重启后日志中会重复打印：envs/xin/lib/python3.10/site-packages/torch/cuda/__init__.py:65: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]

**Comment by codingl2k1** [comment]
> > Tested on V100:
> > <img alt="Image" width="1398" height="588" src="https://private-user-images.githubusercontent.com/138426806/564122181-986ebee7-c9fa-495b-a3f1-23a1bbaef29b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzM2NzM0NjgsIm5iZiI6MTc3MzY3MzE2OCwicGF0aCI6Ii8xMzg0MjY4MDYvNTY0MTIyMTgxLTk4NmViZWU3LWM5ZmEtNDk1Yi1hM2YxLTIzYTFiYmFlZjI5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDMxNlQxNDU5MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZmY1MzQ1M2VkYTc2N2U5Nzk4ODliMzhmMTk3Y2M5MTgxOWZkM2I2ZDg0NjE1MDczMmFkYzE3ZDUzODliOTlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.G7cpnWFCPodivNIXBGGDN0JdSGv1WeD9BghOhk7IRpQ">
> > import xllamacpp as xlc
> > from openai import OpenAI
> > # Start server
> > params = xlc.CommonParams()
> > params.model.path = "/root/Qwen3.5-0.8B-Q4_K_M.gguf"
> > server = xlc.Server(params)
> > # Connect using OpenAI client
> > client = OpenAI(
> > base_url=server.listening_address + "/v1",
> > api_key="not-required"  # No API key needed for local server
> > )
> > # Make chat completion request
> > response = client.chat.completions.create(
> > model="local-model",
> > messages=[{"role": "user", "content": "What is the capital of France?"}],
> > max_tokens=1000
> > )
> > print(response.choices[0].message.content, flush=True)
> 
> 根据代码，可以正常启动并返回。但是Xin服务无法正常启动，换回0.2.7就可以。

我测试 xinference 2.3.0 （关闭 虚拟空间）+ xllamacpp 最新版本正常，无法复现你说的问题。

**Comment by edward687** [comment]
> > > Tested on V100:
> > > <img alt="Image" width="1398" height="588" src="https://private-user-images.githubusercontent.com/138426806/564122181-986ebee7-c9fa-495b-a3f1-23a1bbaef29b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzM2NzM0NjgsIm5iZiI6MTc3MzY3MzE2OCwicGF0aCI6Ii8xMzg0MjY4MDYvNTY0MTIyMTgxLTk4NmViZWU3LWM5ZmEtNDk1Yi1hM2YxLTIzYTFiYmFlZjI5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDMxNlQxNDU5MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZmY1MzQ1M2VkYTc2N2U5Nzk4ODliMzhmMTk3Y2M5MTgxOWZkM2I2ZDg0NjE1MDczMmFkYzE3ZDUzODliOTlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.G7cpnWFCPodivNIXBGGDN0JdSGv1WeD9BghOhk7IRpQ">
> > > import xllamacpp as xlc
> > > from openai import OpenAI
> > > # Start server
> > > params = xlc.CommonParams()
> > > params.model.path = "/root/Qwen3.5-0.8B-Q4_K_M.gguf"
> > > server = xlc.Server(params)
> > > # Connect using OpenAI client
> > > client = OpenAI(
> > > base_url=server.listening_address + "/v1",
> > > api_key="not-required"  # No API key needed for local server
> > > )
> > > # Make chat completion request
> > > response = client.chat.completions.create(
> > > model="local-model",
> > > messages=[{"role": "user", "content": "What is the capital of France?"}],
> > > max_tokens=1000
> > > )
> > > print(response.choices[0].message.content, flush=True)
> > 
> > 
> > 根据代码，可以正常启动并返回。但是Xin服务无法正常启动，换回0.2.7就可以。
> 
> 我测试 xinference 2.3.0 （关闭 虚拟空间）+ xllamacpp 最新版本正常，无法复现你说的问题。

非常感谢回复。我这情况和计划是：1、我倒是没关闭虚拟空间，这个暂时不懂如何关闭；2、计划删掉Xinf后再重新安装试试。

**Comment by edward687** [comment]
目前测试情况如下：
Xinf版本=2.3.0
CUDA=12.8
Python=3.10.19
Xllamacpp版本=https://github.com/xorbitsai/xllamacpp/actions/runs/23137778170 中的12.8版本
①删掉原Xinf环境和文件，重新创建，启动后，仍然日志中无任何信息，虽然Status查看是启动，但是UI无任何动静；
②由于无法正常启动Xinf，无法尝试关闭虚拟空间。

**Comment by codingl2k1** [comment]
> 目前测试情况如下： Xinf版本=2.3.0 CUDA=12.8 Python=3.10.19 Xllamacpp版本=https://github.com/xorbitsai/xllamacpp/actions/runs/23137778170 中的12.8版本 ①删掉原Xinf环境和文件，重新创建，启动后，仍然日志中无任何信息，虽然Status查看是启动，但是UI无任何动静； ②由于无法正常启动Xinf，无法尝试关闭虚拟空间。

你可以卸载掉 xllamacpp 试试看能否启动 xinference

**Comment by codingl2k1** [comment]
xllamacpp 0.2.13 包含了 cuda arch 70 的 fix

**Comment by edward687** [comment]
> > 目前测试情况如下： Xinf版本=2.3.0 CUDA=12.8 Python=3.10.19 Xllamacpp版本=https://github.com/xorbitsai/xllamacpp/actions/runs/23137778170 中的12.8版本 ①删掉原Xinf环境和文件，重新创建，启动后，仍然日志中无任何信息，虽然Status查看是启动，但是UI无任何动静； ②由于无法正常启动Xinf，无法尝试关闭虚拟空间。
> 
> 你可以卸载掉 xllamacpp 试试看能否启动 xinference

卸载xllamacpp或者降低安装0.2.7的wheel可以正常启动xinference
