### ISSUE TITLE
CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by andylzming** [xorbitsai/inference#805]
使用命令启动对话模型，报 cuda 错误。

- 启动命令
`
CUDA_VISIBLE_DEVICES=1 xinference launch -e http://*.*.*.*:59997 -n custom-qwen-chat -u custom-qwen-chat -t LLM -s 14 -f pytorch -q none
`
- 错误日志
`
2023-12-23 22:12:49,855 - modelscope - INFO - PyTorch version 2.1.0+cu121 Found.
2023-12-23 22:12:49,855 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-12-23 22:12:49,881 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 189c42d42c92c9b405fd1509319e1157 and a total number of 946 components indexed
Traceback (most recent call last):
  File "/home/miniconda3/envs/xinference/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/deploy/cmdline.py", line 502, in model_launch
    model_uid = client.launch_model(
  File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/client/restful/restful_client.py", line 669, in launch_model
    raise RuntimeError(
RuntimeError: Failed to launch model, detail: [address=172.22.149.188:34245, pid=22563] CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=1, num_gpus=

CUDA call was originally invoked at:

  File "<string>", line 1, in <module>
  File "/home/miniconda3/envs/xinference/lib/python3.10/multiprocessing/forkserver.py", line 274, in main
    code = _serve_one(child_r, fds,
  File "/home/miniconda3/envs/xinference/lib/python3.10/multiprocessing/forkserver.py", line 313, in _serve_one
    code = spawn._main(child_r, parent_sentinel)
  File "/home/miniconda3/envs/xinference/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/home/miniconda3/envs/xinference/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/miniconda3/envs/xinference/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/home/miniconda3/envs/xinference/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/miniconda3/envs/xinference/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/miniconda3/envs/xinference/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/miniconda3/envs/xinference/bin/xinference-local", line 5, in <module>
    from xinference.deploy.cmdline import local
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/__init__.py", line 32, in <module>
    _install()
  File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/__init__.py", line 29, in _install
    install_model()
  File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/model/__init__.py", line 17, in _install
    from .llm import _install as llm_install
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/model/llm/__init__.py", line 19, in <module>
    from .core import LLM
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/model/llm/core.py", line 22, in <module>
    from ...core.utils import parse_replica_model_uid
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/__init__.py", line 15, in <module>
    from .model import ModelActor
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/model.py", line 49, in <module>
    from torch.cuda import OutOfMemoryError
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/torch/__init__.py", line 1332, in <module>
    _C._initExtension(manager_path())
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/torch/cuda/__init__.py", line 244, in <module>
    _lazy_call(_check_capability)
  File "/home/miniconda3/envs/xinference/lib/python3.10/site-packages/torch/cuda/__init__.py", line 241, in _lazy_call
    _queued_calls.append((callable, traceback.format_stack()))
`

**Comment by aresnow1** [comment]
xinference 更新到最新版本了吗？

**Comment by andylzming** [comment]
不是最新版本，具体版本如下：
`
(xinference) [root@gpu-server ~]# xinference --version
2023-12-24 21:55:22,837 - modelscope - INFO - PyTorch version 2.1.2+cu121 Found.
2023-12-24 21:55:22,837 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-12-24 21:55:22,863 - modelscope - INFO - Loading done! Current index file version is 1.10.0, with md5 189c42d42c92c9b405fd1509319e1157 and a total number of 946 components indexed
xinference, version 0.7.2
`

**Comment by aresnow1** [comment]
这个问题升级到最新版本应该修复了

**Comment by andylzming** [comment]
非常感谢，升级到 0.7.3.1 版本问题解决了。

**Comment by andylzming** [comment]
非常感谢，升级到 0.7.3.1 版本问题解决了。
